apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramitsoni/argocd-demos.git
    targetRevision: main
    path: cli_approach/apache      # Path to apache manifests
  destination:
    server: https://192.168.248.129:33993  # from `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
